name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: darwin-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make package

